/*
CutBridge AE MVP v0.1.0
- Reads cutbridge.json
- Creates deterministic AE folders + comp
- Imports image sequences from manifest
- Basic QC: manifest consistency, pass folder, first-frame source, duration/FPS

Install/test:
File > Scripts > Run Script File... > CutBridge.jsx
For a dockable panel, place this file in After Effects/Scripts/ScriptUI Panels and restart AE.
*/

(function CutBridge(thisObj) {
    var state = {
        manifestFile: null,
        manifest: null,
        packageFolder: null,
        comp: null,
        imported: {}
    };

    function log(msg) {
        $.writeln("[CutBridge] " + msg);
    }

    function alertError(msg) {
        alert("CutBridge\n\n" + msg);
    }

    function readTextFile(file) {
        file.encoding = "UTF-8";
        if (!file.open("r")) throw new Error("Could not open: " + file.fsName);
        var text = file.read();
        file.close();
        return text;
    }

    function parseJSON(text) {
        if (typeof JSON !== "undefined" && JSON.parse) return JSON.parse(text);
        // Fallback for old ExtendScript engines. Manifest is generated by our own tool.
        return eval("(" + text + ")");
    }

    function chooseManifest() {
        var f = File.openDialog("Choose CutBridge cutbridge.json", "JSON:*.json");
        if (!f) return null;
        var obj = parseJSON(readTextFile(f));
        if (!obj || obj.schema !== "cutbridge-manifest") {
            throw new Error("This is not a CutBridge manifest.");
        }
        state.manifestFile = f;
        state.manifest = obj;
        state.packageFolder = f.parent;
        return obj;
    }

    function findChildFolder(parent, name) {
        for (var i = 1; i <= app.project.numItems; i++) {
            var item = app.project.item(i);
            if (item instanceof FolderItem && item.name === name && item.parentFolder === parent) return item;
        }
        var folder = app.project.items.addFolder(name);
        folder.parentFolder = parent;
        return folder;
    }

    function ensureProjectFolders(manifest) {
        var rootName = manifest.package_name || (manifest.project + "_" + manifest.cut);
        var root = findChildFolder(app.project.rootFolder, rootName);
        return {
            root: root,
            comp: findChildFolder(root, "01_COMP"),
            render: findChildFolder(root, "02_RENDER"),
            precomp: findChildFolder(root, "03_PRECOMP"),
            output: findChildFolder(root, "04_OUTPUT")
        };
    }

    function zeroPad(n, width) {
        var s = String(n);
        while (s.length < width) s = "0" + s;
        return s;
    }

    function patternToRegex(pattern) {
        // Supports a single #### style token.
        var escaped = pattern.replace(/([.+^${}()|\[\]\\])/g, "\\$1");
        escaped = escaped.replace(/####/g, "(\\d{4,})");
        return new RegExp("^" + escaped + "$", "i");
    }

    function findFirstSequenceFile(passInfo, manifest) {
        var dir = new Folder(state.packageFolder.fsName + "/" + passInfo.path);
        if (!dir.exists) return null;

        var regex = patternToRegex(passInfo.sequence_pattern);
        var files = dir.getFiles(function(f) { return f instanceof File && regex.test(f.name); });
        if (!files || files.length === 0) return null;

        files.sort(function(a, b) { return a.name < b.name ? -1 : (a.name > b.name ? 1 : 0); });
        return files[0];
    }

    function importSequence(passInfo, manifest, renderFolder) {
        var firstFile = findFirstSequenceFile(passInfo, manifest);
        if (!firstFile) throw new Error("No sequence found for pass " + passInfo.name + " (" + passInfo.sequence_pattern + ")");

        var io = new ImportOptions(firstFile);
        if (io.canImportAs && io.canImportAs(ImportAsType.FOOTAGE)) io.importAs = ImportAsType.FOOTAGE;
        io.sequence = true;
        io.forceAlphabetical = false;

        var footage = app.project.importFile(io);
        footage.name = manifest.cut + "_" + passInfo.name;
        footage.parentFolder = renderFolder;
        try { footage.mainSource.conformFrameRate = manifest.fps; } catch (e) { log("Could not conform FPS for " + passInfo.name + ": " + e.toString()); }
        state.imported[passInfo.name] = footage;
        return footage;
    }

    function findExistingComp(name, parentFolder) {
        for (var i = 1; i <= app.project.numItems; i++) {
            var item = app.project.item(i);
            if (item instanceof CompItem && item.name === name && item.parentFolder === parentFolder) return item;
        }
        return null;
    }

    function buildComp() {
        if (!state.manifest) chooseManifest();
        if (!state.manifest) return;
        if (!app.project) app.newProject();

        var m = state.manifest;
        var folders = ensureProjectFolders(m);
        var compName = (m.ae && m.ae.comp_name) ? m.ae.comp_name : (m.cut + "_COMP");
        var duration = m.frames.count / m.fps;

        app.beginUndoGroup("CutBridge Build Comp");
        try {
            var comp = findExistingComp(compName, folders.comp);
            if (!comp) {
                comp = app.project.items.addComp(
                    compName,
                    m.resolution.width,
                    m.resolution.height,
                    m.resolution.pixel_aspect || 1.0,
                    duration,
                    m.fps
                );
                comp.parentFolder = folders.comp;
            }
            state.comp = comp;

            for (var i = 0; i < m.passes.length; i++) {
                var p = m.passes[i];
                var footage = state.imported[p.name] || importSequence(p, m, folders.render);
                var layer = comp.layers.add(footage);
                layer.name = p.name;
                layer.startTime = 0;
            }

            // Manifest order is top-to-bottom. AE adds new layers at the top, so reorder explicitly.
            if (m.ae && m.ae.layer_order) {
                for (var j = m.ae.layer_order.length - 1; j >= 0; j--) {
                    var lname = m.ae.layer_order[j];
                    for (var k = 1; k <= comp.numLayers; k++) {
                        if (comp.layer(k).name === lname) {
                            comp.layer(k).moveToBeginning();
                            break;
                        }
                    }
                }
            }

            comp.openInViewer();
            alert("CutBridge: comp built\n" + comp.name + "\n" + m.resolution.width + "x" + m.resolution.height + " @ " + m.fps + " fps");
        } catch (e) {
            alertError(e.toString());
        } finally {
            app.endUndoGroup();
        }
    }

    function runQC() {
        if (!state.manifest) chooseManifest();
        if (!state.manifest) return;
        var m = state.manifest;
        var lines = [];
        var errors = 0;

        function ok(msg) { lines.push("OK  " + msg); }
        function bad(msg) { errors++; lines.push("ERR " + msg); }

        if (m.fps > 0) ok("FPS " + m.fps); else bad("Invalid FPS");
        if (m.frames && m.frames.count === (m.frames.end - m.frames.start + 1)) ok("Frame count " + m.frames.count); else bad("Frame count mismatch");
        if (m.resolution && m.resolution.width > 0 && m.resolution.height > 0) ok("Resolution " + m.resolution.width + "x" + m.resolution.height); else bad("Invalid resolution");

        for (var i = 0; i < m.passes.length; i++) {
            var p = m.passes[i];
            var dir = new Folder(state.packageFolder.fsName + "/" + p.path);
            if (!dir.exists) {
                bad(p.name + ": pass folder missing");
                continue;
            }
            var first = findFirstSequenceFile(p, m);
            if (!first) bad(p.name + ": no matching sequence");
            else ok(p.name + ": source found (" + first.name + ")");
        }

        if (state.comp) {
            if (Math.abs(state.comp.frameRate - m.fps) < 0.001) ok("Comp FPS matches manifest"); else bad("Comp FPS mismatch");
            var expectedDuration = m.frames.count / m.fps;
            if (Math.abs(state.comp.duration - expectedDuration) < (1.0 / m.fps)) ok("Comp duration matches manifest"); else bad("Comp duration mismatch");
        }

        alert("CutBridge QC — " + (errors === 0 ? "PASS" : (errors + " issue(s)")) + "\n\n" + lines.join("\n"));
    }

    function loadOnly(statusText) {
        try {
            var m = chooseManifest();
            if (m) statusText.text = (m.package_name || m.cut) + " | " + m.fps + "fps | " + m.frames.count + "f";
        } catch (e) {
            alertError(e.toString());
        }
    }

    function buildUI(thisObj) {
        var pal = (thisObj instanceof Panel) ? thisObj : new Window("palette", "CutBridge", undefined, {resizeable: true});
        if (!pal) return pal;

        pal.orientation = "column";
        pal.alignChildren = ["fill", "top"];
        pal.spacing = 8;
        pal.margins = 12;

        var title = pal.add("statictext", undefined, "CutBridge / カットブリッジ");
        try { title.graphics.font = ScriptUI.newFont(title.graphics.font.name, "BOLD", 16); } catch (e) {}

        var status = pal.add("statictext", undefined, "No package loaded");
        status.characters = 45;

        var btnLoad = pal.add("button", undefined, "1. Import Package / 読み込み");
        var btnBuild = pal.add("button", undefined, "2. Build Comp / コンポ作成");
        var btnQC = pal.add("button", undefined, "3. Run QC / QC実行");

        btnLoad.onClick = function() { loadOnly(status); };
        btnBuild.onClick = function() { buildComp(); };
        btnQC.onClick = function() { runQC(); };

        var note = pal.add("statictext", undefined, "MVP v0.1: package → auto-comp → basic QC", {multiline: true});
        note.preferredSize.height = 32;

        pal.onResizing = pal.onResize = function() { this.layout.resize(); };
        return pal;
    }

    var panel = buildUI(thisObj);
    if (panel instanceof Window) {
        panel.center();
        panel.show();
    } else {
        panel.layout.layout(true);
    }
})(this);
