/* CutBridge S6 revision manager. Pure preflight plus explicit host-adapter transaction boundary. */
(function(root,factory){if(typeof module!=="undefined"&&module.exports)module.exports=factory();else root.CutBridgeRevisionManager=factory();}(this,function(){"use strict";
var SCHEMA="cutbridge-manifest",SCHEMA_VERSION=1,IDS=["project","episode","scene","cut","take"];
function own(o,k){return Object.prototype.hasOwnProperty.call(o,k);} function arr(v){return Object.prototype.toString.call(v)==="[object Array]";} function num(v){return typeof v==="number"&&isFinite(v);}
function identity(m){if(m&&m.package_name)return String(m.package_name);var a=[];for(var i=0;i<IDS.length;i++)a.push(String(m&&m[IDS[i]]));return a.join("|");}
function tag(k,m,p){return"CUTBRIDGE|1|"+k+"|"+identity(m)+"|"+String(p||"");}
function rev(v){if(typeof v==="number"&&isFinite(v))return v;var m=String(v==null?"":v).match(/(?:^|[^0-9])V?([0-9]+)(?:$|[^0-9])/i);return m?parseInt(m[1],10):NaN;}
function map(m){var o={},p=m&&arr(m.passes)?m.passes:[];for(var i=0;i<p.length;i++)o["$"+p[i].name]=p[i];return o;}
function meta(m){return{fps:m&&m.fps,w:m&&m.resolution&&m.resolution.width,h:m&&m.resolution&&m.resolution.height,pa:m&&m.resolution&&m.resolution.pixel_aspect!==undefined?m.resolution.pixel_aspect:1,s:m&&m.frames&&m.frames.start,e:m&&m.frames&&m.frames.end,c:m&&m.frames&&m.frames.count};}
function eq(a,b,e){return num(a)&&num(b)&&Math.abs(a-b)<=e;}
function assess(cur,next){var r=[],w=[],a=meta(cur),b=meta(next);if(!cur||!next)return{status:"incompatible",reasons:["Both current and candidate manifests are required."],warnings:[]};
if(next.schema!==SCHEMA||next.schema_version!==SCHEMA_VERSION)r.push("candidate schema is not supported");if(cur.schema!==SCHEMA||cur.schema_version!==SCHEMA_VERSION)r.push("current schema is not supported");if(identity(cur)!==identity(next))r.push("project/episode/scene/cut/take identity differs");
var cv=rev(cur.version),nv=rev(next.version);if(!num(cv)||!num(nv))r.push("package version is not numeric");else if(nv<=cv)r.push("candidate is not newer");
if(!eq(a.fps,b.fps,.001))r.push("FPS changes are not supported");if(a.s!==b.s||a.e!==b.e||a.c!==b.c)r.push("frame range/count changes are not supported");if(!eq(a.pa,b.pa,.000001))r.push("pixel aspect changes are not supported");if(a.w!==b.w||a.h!==b.h)w.push("resolution changes require explicit confirmation; existing layer geometry is preserved");
var old=map(cur),fresh=map(next),passes=cur.passes||[];for(var i=0;i<passes.length;i++)if(passes[i].required!==false&&!own(fresh,"$"+passes[i].name))r.push("previously required pass is missing: "+passes[i].name);for(var k in old)if(own(old,k)&&!own(fresh,k))w.push("previous pass is absent and will not be deleted: "+old[k].name);
return{status:r.length?"incompatible":w.length?"warning":"safe",reasons:r,warnings:w};}
function select(cur,cands){var a=[],l=arr(cands)?cands:[];for(var i=0;i<l.length;i++){var c=assess(cur,l[i]);if(c.status!=="incompatible")a.push({manifest:l[i],compatibility:c,version:rev(l[i].version)});}a.sort(function(x,y){return y.version-x.version;});return a.length?a[0]:null;}
function discover(cur,cands){var o=[],l=arr(cands)?cands:[];for(var i=0;i<l.length;i++)o.push({manifest:l[i],version:rev(l[i].version),newer:rev(l[i].version)>rev(cur&&cur.version),compatibility:assess(cur,l[i])});o.sort(function(a,b){return b.version-a.version;});return o;}
function plan(cur,next,objects){var c=assess(cur,next),actions=[],o=arr(objects)?objects:[],n=map(next);if(c.status==="incompatible")return{status:c.status,compatibility:c,actions:[],preserve:[]};for(var i=0;i<o.length;i++){var x=o[i],p=x.passName&&n["$"+x.passName];if(x.managed&&x.tag===tag("layer",cur,x.passName)&&p)actions.push({passName:x.passName,layer:x,replacement:p,oldSource:x.source,managedTag:x.tag});}return{status:c.status,compatibility:c,actions:actions,preserve:["layer transforms","effects","masks","parenting","timing","switches","blend modes","manual layers","artist ordering outside managed subset"],requiresConfirmation:c.status==="warning"};}
function apply(p,a,confirmed){if(!p||p.status==="incompatible")throw new Error("Revision is incompatible; no managed objects were changed.");if(p.requiresConfirmation&&confirmed!==true)throw new Error("Revision has warnings and requires explicit confirmation.");if(!a||typeof a.importReplacement!=="function"||typeof a.swapManagedSource!=="function")throw new Error("Revision host adapter must provide importReplacement and swapManagedSource.");var made=[],done=[];try{for(var i=0;i<p.actions.length;i++){var x=p.actions[i],n=a.importReplacement(x.replacement,x.passName);if(!n)throw new Error(x.passName+": replacement import returned no footage.");if(typeof a.validateReplacement==="function"&&a.validateReplacement(n,x.replacement)!==true)throw new Error(x.passName+": replacement footage failed validation.");made.push(n);a.swapManagedSource(x.layer,n);done.push(x);}return{status:"applied",replaced:done.length,imported:made.length};}catch(e){for(var j=done.length-1;j>=0;j--)try{if(typeof a.restoreManagedSource==="function")a.restoreManagedSource(done[j].layer,done[j].oldSource);}catch(ignore){}for(var k=made.length-1;k>=0;k--)try{if(typeof a.removeImportedReplacement==="function")a.removeImportedReplacement(made[k]);}catch(ignore2){}throw e;}}
return{SCHEMA:SCHEMA,SCHEMA_VERSION:SCHEMA_VERSION,identity:identity,managedTag:tag,revisionNumber:rev,assess:assess,discover:discover,selectLatest:select,plan:plan,apply:apply};}));