function cbJson(v){if(v===null||v===undefined)return 'null';if(typeof v==='number'||typeof v==='boolean')return String(v);if(typeof v==='string')return '"'+v.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r/g,'\\r').replace(/\n/g,'\\n').replace(/\t/g,'\\t')+'"';var a=[],i;if(v instanceof Array){for(i=0;i<v.length;i++)a.push(cbJson(v[i]));return '['+a.join(',')+']';}for(i in v)if(v.hasOwnProperty(i))a.push(cbJson(i)+':'+cbJson(v[i]));return '{'+a.join(',')+'}';}
function cbSave(name,r){var f=new File('C:/CutBridgeValidityEvidence/'+name+'.json');if(!f.open('w'))throw Error('Report cannot be written');f.write(cbJson(r));f.close();}
function cbComp(){for(var i=1;i<=app.project.numItems;i++)if(app.project.item(i) instanceof CompItem&&app.project.item(i).name==='C001_COMP')return app.project.item(i);throw Error('Comp not found');}
function cbSnapshot(){var c=cbComp(),a=[];for(var i=1;i<=c.numLayers;i++){var l=c.layer(i),t=l.property('ADBE Transform Group'),opacity=t.property('ADBE Opacity');var keys=[];for(var k=1;opacity&&k<=opacity.numKeys;k++)keys.push({time:opacity.keyTime(k),value:opacity.keyValue(k)});a.push({name:l.name,index:l.index,id:l.id,comment:l.comment,source:l.source&&l.source.file?l.source.file.fsName:null,opacityKeys:keys,opacityExpression:opacity?opacity.expression:null,effects:l.property('ADBE Effect Parade')?l.property('ADBE Effect Parade').numProperties:0,masks:l.property('ADBE Mask Parade')?l.property('ADBE Mask Parade').numProperties:0,enabled:l.enabled,shy:l.shy,parent:l.parent?l.parent.name:null});}return a;}
function cbNear(a,b){if(a instanceof Array){if(!(b instanceof Array)||a.length!==b.length)return false;for(var i=0;i<a.length;i++)if(!cbNear(a[i],b[i]))return false;return true;}return Math.abs(a-b)<0.001;}
function cbHandoff(m){var c=cbComp(),checks=[],h=m.handoff_3d,cam=c.layer(h.camera.name),pos=cam.property('ADBE Transform Group').property('ADBE Position'),poi=cam.property('ADBE Transform Group').property('ADBE Anchor Point'),zoom=cam.property('ADBE Camera Options Group').property('ADBE Camera Zoom');checks.push({name:'camera is native CameraLayer',passed:cam instanceof CameraLayer});for(var i=0;i<h.camera.samples.length;i++){var s=h.camera.samples[i],p=[s.position[0]+s.forward[0]*1000,s.position[1]+s.forward[1]*1000,s.position[2]+s.forward[2]*1000];checks.push({name:'camera sample '+i,passed:cbNear(pos.valueAtTime(s.time,false),s.position)&&cbNear(poi.valueAtTime(s.time,false),p)&&cbNear(zoom.valueAtTime(s.time,false),s.ae_zoom)});}for(i=0;i<h.nulls.length;i++){var n=h.nulls[i],l=c.layer(n.name),t=l.property('ADBE Transform Group');checks.push({name:'native 3D null '+n.name,passed:l.nullLayer&&l.threeDLayer});for(var k=0;k<n.samples.length;k++){s=n.samples[k];checks.push({name:'null sample '+k,passed:cbNear(t.property('ADBE Position').valueAtTime(s.time,false),s.position)&&cbNear(t.property('ADBE Scale').valueAtTime(s.time,false),[s.scale[0]*100,s.scale[1]*100,s.scale[2]*100])});}}return checks;}



